[package]
name = "rs-vec-com"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.4.0"
ark-ec = "0.4.2"
ark-ff = "0.4.2"
ark-std = "0.4.0"
sha2 = "0.10.7"

[dev-dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
